# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: motaz <motaz@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/09/27 00:30:11 by motaz             #+#    #+#              #
#    Updated: 2025/09/27 00:53:25 by motaz            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#program name
NAME = push_swap

CC = cc 
CFLAGS = -Wall -Wextra -Werror

#libft + printf
LIBFT = ./libft_printf/libft/libft.a
PRINTF =  ./libft_printf/printf/libft_printf.a

RM = rm -f
